<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // const PENDING = 'PENDING';
        // const FULFILLED = 'FULFILLED';
        // const REJECTED = 'REJECTED';

        // const resolvePromise = (promise2, x, resolve, reject) => {
        //     // 自己等待自己完成是错误的实现，用一个类型错误，结束掉 promise  Promise/A+ 2.3.1
        //     if (promise2 === x) {
        //         return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
        //     }

        //     let called;
        //     // 后续的条件要严格判断 保证代码能和别的库一起使用
        //     if ((typeof x === 'object' && x != null) || typeof x === 'function') {
        //         try {
        //             // 为了判断 resolve 过的就不用再 reject 了（比如 reject 和 resolve 同时调用的时候）  
        //             const then = x.then;
        //             if (typeof then === 'function') {
        //                 // 不要写成 x.then，直接 then.call 就可以了 因为 x.then 会再次取值，Object.defineProperty  
        //                 then.call(x, y => { // 根据 promise 的状态决定是成功还是失败
        //                     if (called) return;
        //                     called = true;
        //                     // 递归解析的过程（因为可能 promise 中还有 promise） 
        //                     resolvePromise(promise2, y, resolve, reject);
        //                 }, r => {
        //                     // 只要失败就失败 
        //                     if (called) return;
        //                     called = true;
        //                     reject(r);
        //                 });
        //             } else {
        //                 // 如果 x.then 是个普通值就直接返回 resolve 作为结果 
        //                 resolve(x);
        //             }
        //         } catch (e) {
        //             if (called) return;
        //             called = true;
        //             reject(e)
        //         }
        //     } else {
        //         // 如果 x 是个普通值就直接返回 resolve 作为结果  
        //         resolve(x)
        //     }
        // }

        // class Promise {
        //     constructor(executor) {
        //         this.status = PENDING;

        //         this.value = undefined;
        //         this.reason = undefined;

        //         this.onResolvedCallbacks = [];
        //         this.onRejectedCallbacks = [];

        //         const resolve = (value) => {
        //             if (this.status === PENDING) {
        //                 this.status = FULFILLED;
        //                 this.value = value;
        //                 this.onResolvedCallbacks.forEach(fn => fn());
        //             }
        //         }
        //         const reject = (reason) => {
        //             if (this.status === PENDING) {
        //                 this.status = REJECTED;
        //                 this.reason = reason;
        //                 this.onRejectedCallbacks.forEach(fn => fn());
        //             }
        //         }

        //         try {

        //             executor(resolve, reject)
        //         } catch (error) {
        //             reject(error)
        //         }
        //     }

        //     then(onFulfilled, onRejected) {

        //         //解决 onFufilled，onRejected 没有传值的问题

        //         onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : v => v;
        //         //因为错误的值要让后面访问到，所以这里也要跑出个错误，不然会在之后 then 的 resolve 中捕获
        //         onRejected = typeof onRejected === 'function' ? onRejected : err => { throw err };



        //         // 每次调用 then 都返回一个新的 promise  Promise/A+ 2.2.7
        //         const promise2 = new Promise((resolve, reject) => {
        //             // debugger
        //             if (this.status === FULFILLED) {
        //                 setTimeout(() => {
        //                     try {
        //                         const x = onFulfilled(this.value);
        //                         // x可能是一个proimise
        //                         resolvePromise(promise2, x, resolve, reject);
        //                     } catch (e) {
        //                         reject(e)
        //                     }
        //                 }, 0);
        //             }

        //             if (this.status === REJECTED) {
        //                 setTimeout(() => {
        //                     try {
        //                         const x = onRejected(this.reason);
        //                         resolvePromise(promise2, x, resolve, reject);
        //                     } catch (e) {
        //                         reject(e)
        //                     }
        //                 }, 0);
        //             }

        //             if (this.status === PENDING) {
        //                 this.onResolvedCallbacks.push(() => {
        //                     setTimeout(() => {
        //                         try {
        //                             const x = onFulfilled(this.value);
        //                             resolvePromise(promise2, x, resolve, reject);
        //                         } catch (e) {
        //                             reject(e)
        //                         }
        //                     }, 0);
        //                 });

        //                 this.onRejectedCallbacks.push(() => {
        //                     setTimeout(() => {
        //                         try {
        //                             const x = onRejected(this.reason);
        //                             resolvePromise(promise2, x, resolve, reject)
        //                         } catch (e) {
        //                             reject(e)
        //                         }
        //                     }, 0);
        //                 });
        //             }
        //         });
        //         return promise2;
        //     }
        // }


        // 原生的promise
        // const promise_1 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve("成功")
        //     }, 1000)
        // })
        // const promise_2 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         reject("失败了")
        //     }, 2000)
        // })
        // Promise.all([promise_1, promise_2]).then(res => {
        //     console.log("Promise.all-success", res)
        // }, error => {
        //     console.log("Promise.all-error", error)
        // })


        // 简易版本 
        class myPromise {
            status = "pending"
            successData = undefined
            errerData = undefined
            successCallbacks = []
            errorCallbacks = []
            constructor(callback) {


                try {
                    callback(this.resolve.bind(this), this.reject.bind(this))
                } catch (e) {
                    this.reject.bind(this)(e)
                }
            }
            resolve(value) {
                if (this.status === "pending") {
                    this.status = "resolve"
                    this.successData = value
                    this.successCallbacks.forEach(fn => fn())
                }
            }

            reject(value) {
                if (this.status === "pending") {
                    this.status = "reject"
                    this.errerData = value
                    this.errorCallbacks.forEach(fn => fn())
                }

            }

            then(resolveFunction, rejectFunction) {
                if (this.status === "resolve") {
                    resolveFunction(this.successData)
                }
                if (this.status === "reject") {
                    rejectFunction(this.errerData)
                }
                if (this.status === "pending") {
                    this.successCallbacks.push(() => {
                        resolveFunction(this.successData)
                    })
                    this.errorCallbacks.push(() => {
                        rejectFunction(this.errerData)
                    })
                }
            }
        }

        myPromise.all = function (promiseList) {
            const resultList = []
            let resolveLen = 0
            let hasErr = false
            return new myPromise((resolve, reject) => {
                for (let i = 0; i < promiseList.length; i++) {
                    promiseList[i].then(data => {
                        console.log("data", data)
                        resultList[i] = data
                        resolveLen++
                        // 如果搜有的promise 都是执行的resolve 然后执行的promise 的resolve
                        resolveLen === promiseList.length && resolve(resultList)
                    }, error => {
                        console.log("error", error)
                        !hasErr && reject(error)
                        hasErr = true
                    })
                }
            })
        }


        myPromise.race = function (promiseList) {
            let hasValue = false
            let hasError = false
            return new myPromise((resolve, reject) => {
                for (let i = 0; i < promiseList.length; i++) {
                    promiseList[i].then(data => {
                        !hasValue && !hasError && resolve(data)
                        hasValue = true
                    }, error => {
                        !hasValue && !hasError && reject(error)
                        hasError = true
                    })
                }
            })
        }
        // const mypromise_1 = new myPromise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve("成功了")
        //     }, 1000)
        // })
        const mypromise_2 = new myPromise((resolve, reject) => {
            setTimeout(() => {
                reject("失败了")
            }, 3000)
        }).then(res => { }, err => {
            console.log("promise2", err)
        })


        // myPromise.all([mypromise_1, mypromise_2]).then(res => {
        //     console.log("mypromise-all-success", res)
        // }, error => {
        //     console.log("mypromise-all-error", error)
        // })
        // myPromise.race([mypromise_1, mypromise_2]).then(res => {
        //     console.log("mypromise-race-success", res)
        // }, error => {
        //     console.log("mypromise-race-error", error)
        // })
        const promise1 = new myPromise((resolve, reject) => {
            setTimeout(() => {
                resolve("成功了")
            }, 2000)
        })
        const promise2 = new myPromise((resolve, reject) => {
            setTimeout(() => {
                resolve("成功了")
            }, 1000)
        })

        const promise3 = new myPromise((resolve, reject) => {
            setTimeout(() => {
                reject("失败了")
            }, 3000)
        })
        myPromise.all([promise1, promise2, promise3]).then(res => {
            console.log("mypromise-all-success", res)
        }, error => {
            console.log("mypromise-all-error", error)
        })

        // class Promise2 {
        //     succeed = null
        //     fail = null
        //     state = 'pending'

        //     constructor(fn) {
        //         fn(this.resolve.bind(this), this.reject.bind(this))
        //     }

        //     resolve(result) {
        //         setTimeout(() => {
        //             this.state = 'fulfilled'
        //             this.succeed(result)
        //         })
        //     }

        //     reject(reason) {
        //         setTimeout(() => {
        //             this.state = 'rejected'
        //             this.fail(reason)
        //         })
        //     }

        //     then(succeed, fail) {
        //         this.succeed = succeed
        //         this.fail = fail
        //     }
        // }
        // Promise2.all = function (arrP) {
        //     const list = []
        //     let len = 0
        //     let hasErr = false
        //     return new Promise2((resolve, reject) => {
        //         for (let i = 0; i < arrP.length; i++) {
        //             arrP[i].then(data => {
        //                 list[i] = data
        //                 len++
        //                 len === arrP.length && resolve(list)
        //             }, error => {
        //                 !hasErr && reject(error)
        //                 hasErr = true
        //             })
        //         }
        //     })
        // }
        // const promise2_1 = new Promise2((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve("成功了")

        //     }, 1000)
        // })
        // const promise2_2 = new Promise2((resolve, reject) => {
        //     setTimeout(() => {
        //         reject("失败了")
        //     }, 3000)
        // })

        // Promise2.all([promise2_1, promise2_2]).then(res => {
        //     console.log("Promise2.all-success", res)
        // }, error => {
        //     console.log("Promise2.all-error", error)
        // })




    </script>
</body>

</html>