<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        const PENDING = 'PENDING';
        const FULFILLED = 'FULFILLED';
        const REJECTED = 'REJECTED';

        const resolvePromise = (promise2, x, resolve, reject) => {
            // 自己等待自己完成是错误的实现，用一个类型错误，结束掉 promise  Promise/A+ 2.3.1
            if (promise2 === x) {
                return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
            }

            let called;
            // 后续的条件要严格判断 保证代码能和别的库一起使用
            if ((typeof x === 'object' && x != null) || typeof x === 'function') {
                try {
                    // 为了判断 resolve 过的就不用再 reject 了（比如 reject 和 resolve 同时调用的时候）  
                    const then = x.then;
                    if (typeof then === 'function') {
                        // 不要写成 x.then，直接 then.call 就可以了 因为 x.then 会再次取值，Object.defineProperty  
                        then.call(x, y => { // 根据 promise 的状态决定是成功还是失败
                            if (called) return;
                            called = true;
                            // 递归解析的过程（因为可能 promise 中还有 promise） 
                            resolvePromise(promise2, y, resolve, reject);
                        }, r => {
                            // 只要失败就失败 
                            if (called) return;
                            called = true;
                            reject(r);
                        });
                    } else {
                        // 如果 x.then 是个普通值就直接返回 resolve 作为结果 
                        resolve(x);
                    }
                } catch (e) {
                    if (called) return;
                    called = true;
                    reject(e)
                }
            } else {
                // 如果 x 是个普通值就直接返回 resolve 作为结果  
                resolve(x)
            }
        }

        class Promise {
            constructor(executor) {
                this.status = PENDING;

                this.value = undefined;
                this.reason = undefined;

                this.onResolvedCallbacks = [];
                this.onRejectedCallbacks = [];

                const resolve = (value) => {
                    if (this.status === PENDING) {
                        this.status = FULFILLED;
                        this.value = value;
                        this.onResolvedCallbacks.forEach(fn => fn());
                    }
                }
                const reject = (reason) => {
                    if (this.status === PENDING) {
                        this.status = REJECTED;
                        this.reason = reason;
                        this.onRejectedCallbacks.forEach(fn => fn());
                    }
                }

                try {

                    executor(resolve, reject)
                } catch (error) {
                    reject(error)
                }
            }

            then(onFulfilled, onRejected) {

                //解决 onFufilled，onRejected 没有传值的问题

                onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : v => v;
                //因为错误的值要让后面访问到，所以这里也要跑出个错误，不然会在之后 then 的 resolve 中捕获
                onRejected = typeof onRejected === 'function' ? onRejected : err => { throw err };



                // 每次调用 then 都返回一个新的 promise  Promise/A+ 2.2.7
                const promise2 = new Promise((resolve, reject) => {
                    // debugger
                    if (this.status === FULFILLED) {
                        setTimeout(() => {
                            try {
                                const x = onFulfilled(this.value);
                                // x可能是一个proimise
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (e) {
                                reject(e)
                            }
                        }, 0);
                    }

                    if (this.status === REJECTED) {
                        setTimeout(() => {
                            try {
                                const x = onRejected(this.reason);
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (e) {
                                reject(e)
                            }
                        }, 0);
                    }

                    if (this.status === PENDING) {
                        this.onResolvedCallbacks.push(() => {
                            setTimeout(() => {
                                try {
                                    const x = onFulfilled(this.value);
                                    resolvePromise(promise2, x, resolve, reject);
                                } catch (e) {
                                    reject(e)
                                }
                            }, 0);
                        });

                        this.onRejectedCallbacks.push(() => {
                            setTimeout(() => {
                                try {
                                    const x = onRejected(this.reason);
                                    resolvePromise(promise2, x, resolve, reject)
                                } catch (e) {
                                    reject(e)
                                }
                            }, 0);
                        });
                    }
                });
                return promise2;
            }
        }


        // 原生的promise
        // const promise = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve("成功")
        //     }, 1000)
        //     // resolve("成功")
        // }).then().then(res => {
        //     console.log('success', res)
        // }, rej => {
        //     console.log('error', rej)
        // })
        // 简易版本 
        class myPromise {
            constructor(callback) {
                this.status = "pending"
                this.successData = undefined
                this.errerData = undefined

                this.successCallbacks = []
                this.errorCallbacks = []
                const resolve = (value) => {
                    if (this.status === "pending") {
                        this.status = "resolve"
                        this.successData = value
                        this.successCallbacks.forEach(fn => fn())
                    }
                }
                const reject = (value) => {
                    this.status = "reject"
                    this.errerData = value
                    this.errorCallbacks.forEach(fn => fn())
                }
                try {
                    callback(resolve, reject)
                } catch (e) {
                    reject(e)
                }
            }
            then(resolveFunction, rejectFunction) {
                if (this.status === "resolve") {
                    resolveFunction(this.successData)
                }
                if (this.status === "reject") {
                    rejectFunction(this.errerData)
                }
                if (this.status === "pending") {
                    this.successCallbacks.push(() => {
                        resolveFunction(this.successData)
                    })
                    this.errorCallbacks.push(() => {
                        rejectFunction(this.errerData)
                    })
                }
            }
        }
        const mypromise = new myPromise((resolve, reject) => {
            setTimeout(() => {
                resolve("成功了")
            }, 1000)
        }).then(res => {
            console.log(res)
        })
    </script>
</body>

</html>